swagger: "2.0"
info:
  description: "Deusolved에 필요한 API를 제작해서 설명을 여기로 합니다.\
  API직접 테스트를 해보고 싶으면 API툴에서 직접 시도해보시기 바람니다."
  version: "1.0.5"
  title: "Deusolved Api"
tags:
  - name: "ascode"
    description: "ascode 관한 API 모음 주소:https://deusolved.swdev.kr/ascode/"
  - name: "login"
    description: "deusolved 로그인 관한 API 모음 주소:https://deusolved.swdev.kr/login/"
paths:
   /api/ascodelogin:
    get:
      tags:
        - "ascode"
      summary: "AScode에 로그인 요청을 보내서 유저를 판정합니다."
      parameters:
        - name: id
          in: string
          schema:
            type: string
        - name: password
          in: string
          schema:
            type: string
