swagger: "2.0"
info:
  description: "Deusolved에 필요한 API를 제작해서 설명을 여기로 합니다."
  version: "1.0.5"
  title: "Deusolved Api"
servers:
  - url: https://deusolved-testapi.swdev.kr/ascode/
     description: Ascode 관련 APi 도메인
  - url: https://deusolved-testapi.swdev.kr/login/
     description: 로그인관련 API 도메인
  - url: https://deusolved-testapi.swdev.kr/judge/
    description: 저지사이트 관련 API 도메인
tags:
  - name: "ascode"
    description: "ascode 관한 API 모음"
paths:
  ascode/api/ascodelogin:
    get:
      tags:
        - "ascode"
      summary: "AScode에 로그인 요청을 보내서 유저를 판정합니다."
      parameters:
        - name: id
          in: query
          schema:
            type: string
        - name: password
          in: query
          schema:
            type: string
