swagger: "2.0"
info:
  description: "이 페이지는 제가 제작한 API의 사용 예시를 간단히 소개하는 곳입니다."
  version: "1.0.5"
  title: "INMD1 Make API"
servers:
  - url: https://deusolved-testapi.swdev.kr
tags:
  - name: "api/ascode"
    description: "ascode 관한 API 모음"
paths:
  /api/ascode/ascodelogin:
    get:
      tags:
        - "api/ascode"
      summary: "AScode에 로그인 요청을 보내서 유저를 판정합니다."
      parameters:
        - name: id
          in: query
          schema:
            type: string
        - name: password
          in: query
          schema:
            type: string
